<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Description>A dotnet library that's able to run embedded npm environments during runtime.</Description>
		<Authors>zortracks</Authors>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>

</Project>
